server:
  port: 8040
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/longyuanbing/configs/           # 配置git仓库的地址
          search-paths: configs                                # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: longyuanbing                                           # git仓库的账号
          password: lyb19860603                                             # git仓库的密码